# Generated by Django 4.1.1 on 2022-09-25 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cotization_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dollar',
            name='stamp',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
