# Generated by Django 4.1.1 on 2022-10-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotization_api', '0002_dollar_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollar',
            name='price',
            field=models.FloatField(),
        ),
    ]
